---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-pvc
spec:

  accessModes:
    - ReadWriteOnce
  storageClassName: sql-ebs-gp3-sc
  resources:
    requests:
      storage: 50Gi
...
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: wordpress-ebs-gp3-sc
  resources:
    requests:
      storage: 10Gi
...