---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
      tier: mysql
  ports:
    - port: 3306
      name: sql
  type: ClusterIP 
...
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
spec:
  selector:
      tier: frontend
  ports:
    - port: 80
      name: http
  type: LoadBalancer 