---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: sql-ebs-gp3-sc
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
...
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: wordpress-ebs-gp3-sc
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
...